
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lucas Gonçalves da Cruz - RA: 202412055
           Emily da Silveira - RA: 1072418263
           Guilherme Wolowski Rodrigues - RA: 12923118494
 */
public class testedengue extends javax.swing.JFrame {

    /**
     * Creates new form testedengue
     */
    public testedengue() {
        initComponents();
         initCheckboxes();
        
    }
    private void initCheckboxes() {
    sim1.addActionListener(e -> toggleCheckbox(sim1, nao1));
    nao1.addActionListener(e -> toggleCheckbox(nao1, sim1));
    sim2.addActionListener(e -> toggleCheckbox(sim2, nao2));
    nao2.addActionListener(e -> toggleCheckbox(nao2, sim2));
    sim3.addActionListener(e -> toggleCheckbox(sim3, nao3));
    nao3.addActionListener(e -> toggleCheckbox(nao3, sim3));
    sim4.addActionListener(e -> toggleCheckbox(sim4, nao4));
    nao4.addActionListener(e -> toggleCheckbox(nao4, sim4));
    sim5.addActionListener(e -> toggleCheckbox(sim5, nao5));
    nao5.addActionListener(e -> toggleCheckbox(nao5, sim5));
    sim6.addActionListener(e -> toggleCheckbox(sim6, nao6));
    nao6.addActionListener(e -> toggleCheckbox(nao6, sim6));
    sim7.addActionListener(e -> toggleCheckbox(sim7, nao7));
    nao7.addActionListener(e -> toggleCheckbox(nao7, sim7));
    sim8.addActionListener(e -> toggleCheckbox(sim8, nao8));
    nao8.addActionListener(e -> toggleCheckbox(nao8, sim8));
    sim9.addActionListener(e -> toggleCheckbox(sim9, nao9));
    nao9.addActionListener(e -> toggleCheckbox(nao9, sim9));
    sim10.addActionListener(e -> toggleCheckbox(sim10, nao10));
    nao10.addActionListener(e -> toggleCheckbox(nao10, sim10));
}

private void toggleCheckbox(JCheckBox selected, JCheckBox toDisable) {
    if (selected.isSelected()) {
        toDisable.setEnabled(false);
    } else {
        toDisable.setEnabled(true);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sim1 = new javax.swing.JCheckBox();
        nao1 = new javax.swing.JCheckBox();
        sim2 = new javax.swing.JCheckBox();
        nao2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        sim3 = new javax.swing.JCheckBox();
        nao3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        sim4 = new javax.swing.JCheckBox();
        nao4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sim5 = new javax.swing.JCheckBox();
        nao5 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        sim6 = new javax.swing.JCheckBox();
        nao6 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        sim7 = new javax.swing.JCheckBox();
        nao7 = new javax.swing.JCheckBox();
        nao8 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        sim8 = new javax.swing.JCheckBox();
        nao9 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        sim9 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        nao10 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        sim10 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Teste de Dengue");

        jLabel2.setText("1. Febre acima de 39 Graus");

        sim1.setText("Sim");
        sim1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao1.setText("Não");
        nao1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sim2.setText("Sim");
        sim2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao2.setText("Não");
        nao2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("2. Enjoos, vômitos ou/e diarreia");

        sim3.setText("Sim");
        sim3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao3.setText("Não");
        nao3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setText("3. Dor de cabeça constante");

        sim4.setText("Sim");
        sim4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao4.setText("Não");
        nao4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("4. Dor no fundo dos olhos");

        jLabel6.setText("5. Manchas vermelhas na pele, em todo o corpo");

        sim5.setText("Sim");
        sim5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao5.setText("Não");
        nao5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("6. Cansaço excessivo sem razão aparente");

        sim6.setText("Sim");
        sim6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao6.setText("Não");
        nao6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("7. Dor nas articulações e ossos");

        sim7.setText("Sim");
        sim7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao7.setText("Não");
        nao7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao8.setText("Não");
        nao8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setText("8. Sangramento pelo nariz, olhos ou gengivas");

        sim8.setText("Sim");
        sim8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nao9.setText("Não");
        nao9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setText("9. Urina rosa, vermelha ou marrom");

        sim9.setText("Sim");
        sim9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setForeground(new java.awt.Color(102, 255, 51));
        jButton1.setText("Enviar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nao10.setText("Não");
        nao10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setText("10. Fezes com sangue ou/e escuras.");

        sim10.setText("Sim");
        sim10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Clique aqui");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("By: Lucas Gonçalves da Cruz - RA: 202412055");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Emily da Silveira - RA: 1072418263");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Guilherme Wolowski Rodrigues - RA: 12923118494");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nao10)
                            .addComponent(sim10)
                            .addComponent(nao9)
                            .addComponent(sim9)
                            .addComponent(nao8)
                            .addComponent(sim8)
                            .addComponent(nao7)
                            .addComponent(sim7)
                            .addComponent(nao6)
                            .addComponent(sim6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nao3)
                                    .addComponent(sim3)
                                    .addComponent(nao4)
                                    .addComponent(sim4)
                                    .addComponent(nao5)
                                    .addComponent(sim5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nao2)
                                    .addComponent(sim2)
                                    .addComponent(nao1)
                                    .addComponent(sim1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sim2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sim4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sim5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sim10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nao10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel11)))
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    if (!((sim1.isSelected() || nao1.isSelected()) &&
          (sim2.isSelected() || nao2.isSelected()) &&
          (sim3.isSelected() || nao3.isSelected()) &&
          (sim4.isSelected() || nao4.isSelected()) &&
          (sim5.isSelected() || nao5.isSelected()) &&
          (sim6.isSelected() || nao6.isSelected()) &&
          (sim7.isSelected() || nao7.isSelected()) &&
          (sim8.isSelected() || nao8.isSelected()) &&
          (sim9.isSelected() || nao9.isSelected()) &&
          (sim10.isSelected() || nao10.isSelected()))) {
        JOptionPane.showMessageDialog(this, "Opção(es) não selecionada(s).");
        return;
    }

   
    if ((sim1.isSelected() && nao1.isSelected()) || 
        (sim2.isSelected() && nao2.isSelected()) || 
        (sim3.isSelected() && nao3.isSelected()) || 
        (sim4.isSelected() && nao4.isSelected()) || 
        (sim5.isSelected() && nao5.isSelected()) || 
        (sim6.isSelected() && nao6.isSelected()) || 
        (sim7.isSelected() && nao7.isSelected()) || 
        (sim8.isSelected() && nao8.isSelected()) || 
        (sim9.isSelected() && nao9.isSelected()) || 
        (sim10.isSelected() && nao10.isSelected())) {
        JOptionPane.showMessageDialog(this, "Cada linha deve ter apenas uma opção marcada: 'Sim' ou 'Não'.");
        return;
    }

    
    boolean sim5Marcada = sim5.isSelected();
    boolean sim1a4Marcada = sim1.isSelected() || sim2.isSelected() || sim3.isSelected() || sim4.isSelected();
    boolean sim8Marcada = sim8.isSelected();
    boolean sim9Marcada = sim9.isSelected();
    boolean sim10Marcada = sim10.isSelected();
    boolean outroSimMarcado = sim1.isSelected() || sim2.isSelected() || sim3.isSelected() || sim4.isSelected() ||
                              sim6.isSelected() || sim7.isSelected();

    if (sim5Marcada && outroSimMarcado) {
        JOptionPane.showMessageDialog(this, "Você pode estar com Dengue, consulte um médico.");
    } else if (sim1a4Marcada && (sim5.isSelected() || sim7.isSelected())) {
        JOptionPane.showMessageDialog(this, "Você pode estar com Dengue, consulte um médico.");
    } else if ((sim8Marcada || sim9Marcada || sim10Marcada) && (outroSimMarcado || (sim8Marcada && sim9Marcada) || (sim8Marcada && sim10Marcada) || (sim9Marcada && sim10Marcada))) {
        JOptionPane.showMessageDialog(this, "ATENÇÃO! Você pode estar com Dengue Hemorrágica, consulte um MÉDICO.");
    } else {
        JOptionPane.showMessageDialog(this, "Você possivelmente não tem dengue, porém para um teste mais aprofundado consulte um médico.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed
public class LinkExample {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Link Exemplo");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 200);

        JLabel linkLabel = new JLabel("<html><a href=''>Instagram</a></html>");
        linkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));

        linkLabel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("https://www.instagram.com/crosscyberedge/"));
                } catch (IOException | URISyntaxException ex) {
                    ex.printStackTrace();
                }
            }
        });

        frame.getContentPane().setLayout(new FlowLayout());
        frame.getContentPane().add(linkLabel);
        frame.setVisible(true);
    }
}
    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
     try {
        Desktop.getDesktop().browse(new URI("https://www.instagram.com/crosscyberedge/"));
    } catch (IOException | URISyntaxException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testedengue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testedengue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testedengue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testedengue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testedengue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox nao1;
    private javax.swing.JCheckBox nao10;
    private javax.swing.JCheckBox nao2;
    private javax.swing.JCheckBox nao3;
    private javax.swing.JCheckBox nao4;
    private javax.swing.JCheckBox nao5;
    private javax.swing.JCheckBox nao6;
    private javax.swing.JCheckBox nao7;
    private javax.swing.JCheckBox nao8;
    private javax.swing.JCheckBox nao9;
    private javax.swing.JCheckBox sim1;
    private javax.swing.JCheckBox sim10;
    private javax.swing.JCheckBox sim2;
    private javax.swing.JCheckBox sim3;
    private javax.swing.JCheckBox sim4;
    private javax.swing.JCheckBox sim5;
    private javax.swing.JCheckBox sim6;
    private javax.swing.JCheckBox sim7;
    private javax.swing.JCheckBox sim8;
    private javax.swing.JCheckBox sim9;
    // End of variables declaration//GEN-END:variables
}
